# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inscripcion.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1247, 927)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setBaseSize(QtCore.QSize(1000, 800))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 246, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-20, 60, 1281, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_33 = QtGui.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(30, 410, 246, 18))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(30, 700, 141, 18))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gBoxTrab = QtGui.QGroupBox(Form)
        self.gBoxTrab.setEnabled(True)
        self.gBoxTrab.setGeometry(QtCore.QRect(40, 730, 121, 69))
        self.gBoxTrab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gBoxTrab.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxTrab.setObjectName(_fromUtf8("gBoxTrab"))
        self.rBtnSi = QtGui.QRadioButton(self.gBoxTrab)
        self.rBtnSi.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.rBtnSi.setObjectName(_fromUtf8("rBtnSi"))
        self.rBtnNo = QtGui.QRadioButton(self.gBoxTrab)
        self.rBtnNo.setGeometry(QtCore.QRect(60, 30, 41, 20))
        self.rBtnNo.setChecked(True)
        self.rBtnNo.setObjectName(_fromUtf8("rBtnNo"))
        self.gBDocs = QtGui.QGroupBox(Form)
        self.gBDocs.setGeometry(QtCore.QRect(40, 820, 1181, 64))
        self.gBDocs.setObjectName(_fromUtf8("gBDocs"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.gBDocs)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.cBDni = QtGui.QCheckBox(self.gBDocs)
        self.cBDni.setObjectName(_fromUtf8("cBDni"))
        self.horizontalLayout_15.addWidget(self.cBDni)
        spacerItem = QtGui.QSpacerItem(99, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.cBTit = QtGui.QCheckBox(self.gBDocs)
        self.cBTit.setObjectName(_fromUtf8("cBTit"))
        self.horizontalLayout_15.addWidget(self.cBTit)
        spacerItem1 = QtGui.QSpacerItem(99, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.cBReg = QtGui.QCheckBox(self.gBDocs)
        self.cBReg.setObjectName(_fromUtf8("cBReg"))
        self.horizontalLayout_15.addWidget(self.cBReg)
        spacerItem2 = QtGui.QSpacerItem(99, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.cBFoto = QtGui.QCheckBox(self.gBDocs)
        self.cBFoto.setObjectName(_fromUtf8("cBFoto"))
        self.horizontalLayout_15.addWidget(self.cBFoto)
        spacerItem3 = QtGui.QSpacerItem(99, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.cBCert = QtGui.QCheckBox(self.gBDocs)
        self.cBCert.setObjectName(_fromUtf8("cBCert"))
        self.horizontalLayout_15.addWidget(self.cBCert)
        self.BtnOk = QtGui.QPushButton(Form)
        self.BtnOk.setGeometry(QtCore.QRect(979, 900, 101, 22))
        self.BtnOk.setObjectName(_fromUtf8("BtnOk"))
        self.BtnCancel = QtGui.QPushButton(Form)
        self.BtnCancel.setGeometry(QtCore.QRect(1100, 900, 101, 22))
        self.BtnCancel.setObjectName(_fromUtf8("BtnCancel"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 430, 1191, 261))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_8.addWidget(self.label_24)
        self.lntitulo = QtGui.QLineEdit(self.layoutWidget)
        self.lntitulo.setObjectName(_fromUtf8("lntitulo"))
        self.horizontalLayout_8.addWidget(self.lntitulo)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.dEEgr = QtGui.QDateEdit(self.layoutWidget)
        self.dEEgr.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dEEgr.setCalendarPopup(False)
        self.dEEgr.setObjectName(_fromUtf8("dEEgr"))
        self.horizontalLayout_8.addWidget(self.dEEgr)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_9.addWidget(self.label_27)
        self.lnEscuela = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEscuela.sizePolicy().hasHeightForWidth())
        self.lnEscuela.setSizePolicy(sizePolicy)
        self.lnEscuela.setObjectName(_fromUtf8("lnEscuela"))
        self.horizontalLayout_9.addWidget(self.lnEscuela)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_9.addWidget(self.label_25)
        self.lnDistrito = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnDistrito.sizePolicy().hasHeightForWidth())
        self.lnDistrito.setSizePolicy(sizePolicy)
        self.lnDistrito.setObjectName(_fromUtf8("lnDistrito"))
        self.horizontalLayout_9.addWidget(self.lnDistrito)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_10.addWidget(self.label_28)
        self.lnOtros = QtGui.QLineEdit(self.layoutWidget)
        self.lnOtros.setObjectName(_fromUtf8("lnOtros"))
        self.horizontalLayout_10.addWidget(self.lnOtros)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_11.addWidget(self.label_29)
        self.lnInsti1 = QtGui.QLineEdit(self.layoutWidget)
        self.lnInsti1.setObjectName(_fromUtf8("lnInsti1"))
        self.horizontalLayout_11.addWidget(self.lnInsti1)
        self.label_31 = QtGui.QLabel(self.layoutWidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_11.addWidget(self.label_31)
        self.dEEgr_2 = QtGui.QDateEdit(self.layoutWidget)
        self.dEEgr_2.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dEEgr_2.setCalendarPopup(False)
        self.dEEgr_2.setObjectName(_fromUtf8("dEEgr_2"))
        self.horizontalLayout_11.addWidget(self.dEEgr_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_30 = QtGui.QLabel(self.layoutWidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_12.addWidget(self.label_30)
        self.lnInsti2 = QtGui.QLineEdit(self.layoutWidget)
        self.lnInsti2.setObjectName(_fromUtf8("lnInsti2"))
        self.horizontalLayout_12.addWidget(self.lnInsti2)
        self.label_32 = QtGui.QLabel(self.layoutWidget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_12.addWidget(self.label_32)
        self.dEEgr_3 = QtGui.QDateEdit(self.layoutWidget)
        self.dEEgr_3.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dEEgr_3.setCalendarPopup(False)
        self.dEEgr_3.setObjectName(_fromUtf8("dEEgr_3"))
        self.horizontalLayout_12.addWidget(self.dEEgr_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(32, 13, 1191, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.line_2 = QtGui.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_7.addWidget(self.line_2)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.cBCarrera = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBCarrera.sizePolicy().hasHeightForWidth())
        self.cBCarrera.setSizePolicy(sizePolicy)
        self.cBCarrera.setObjectName(_fromUtf8("cBCarrera"))
        self.cBCarrera.addItem(_fromUtf8(""))
        self.cBCarrera.addItem(_fromUtf8(""))
        self.cBCarrera.addItem(_fromUtf8(""))
        self.cBCarrera.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cBCarrera)
        spacerItem5 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lnCiclo = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnCiclo.sizePolicy().hasHeightForWidth())
        self.lnCiclo.setSizePolicy(sizePolicy)
        self.lnCiclo.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.lnCiclo.setCursorPosition(0)
        self.lnCiclo.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lnCiclo.setObjectName(_fromUtf8("lnCiclo"))
        self.horizontalLayout_7.addWidget(self.lnCiclo)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(191, 714, 1031, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        self.label_23.setEnabled(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_13.addWidget(self.label_23)
        self.lnAct = QtGui.QLineEdit(self.layoutWidget2)
        self.lnAct.setEnabled(True)
        self.lnAct.setObjectName(_fromUtf8("lnAct"))
        self.horizontalLayout_13.addWidget(self.lnAct)
        self.label_35 = QtGui.QLabel(self.layoutWidget2)
        self.label_35.setEnabled(True)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_13.addWidget(self.label_35)
        self.lnHorario = QtGui.QLineEdit(self.layoutWidget2)
        self.lnHorario.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnHorario.sizePolicy().hasHeightForWidth())
        self.lnHorario.setSizePolicy(sizePolicy)
        self.lnHorario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lnHorario.setObjectName(_fromUtf8("lnHorario"))
        self.horizontalLayout_13.addWidget(self.lnHorario)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(191, 757, 1031, 41))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_36 = QtGui.QLabel(self.layoutWidget3)
        self.label_36.setEnabled(True)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_14.addWidget(self.label_36)
        self.lnOS = QtGui.QLineEdit(self.layoutWidget3)
        self.lnOS.setEnabled(True)
        self.lnOS.setObjectName(_fromUtf8("lnOS"))
        self.horizontalLayout_14.addWidget(self.lnOS)
        self.label_37 = QtGui.QLabel(self.layoutWidget3)
        self.label_37.setEnabled(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_14.addWidget(self.label_37)
        self.lnTelEmer = QtGui.QLineEdit(self.layoutWidget3)
        self.lnTelEmer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnTelEmer.sizePolicy().hasHeightForWidth())
        self.lnTelEmer.setSizePolicy(sizePolicy)
        self.lnTelEmer.setObjectName(_fromUtf8("lnTelEmer"))
        self.horizontalLayout_14.addWidget(self.lnTelEmer)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 140, 1191, 261))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lnNombre = QtGui.QLineEdit(self.widget)
        self.lnNombre.setObjectName(_fromUtf8("lnNombre"))
        self.horizontalLayout.addWidget(self.lnNombre)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.cBSexo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBSexo.sizePolicy().hasHeightForWidth())
        self.cBSexo.setSizePolicy(sizePolicy)
        self.cBSexo.setObjectName(_fromUtf8("cBSexo"))
        self.cBSexo.addItem(_fromUtf8(""))
        self.cBSexo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cBSexo)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.sBEdad = QtGui.QSpinBox(self.widget)
        self.sBEdad.setObjectName(_fromUtf8("sBEdad"))
        self.horizontalLayout.addWidget(self.sBEdad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lnDni = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnDni.sizePolicy().hasHeightForWidth())
        self.lnDni.setSizePolicy(sizePolicy)
        self.lnDni.setObjectName(_fromUtf8("lnDni"))
        self.horizontalLayout_2.addWidget(self.lnDni)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.dENac = QtGui.QDateEdit(self.widget)
        self.dENac.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.dENac.setWrapping(True)
        self.dENac.setAccelerated(True)
        self.dENac.setCalendarPopup(True)
        self.dENac.setObjectName(_fromUtf8("dENac"))
        self.horizontalLayout_2.addWidget(self.dENac)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lnLugar = QtGui.QLineEdit(self.widget)
        self.lnLugar.setObjectName(_fromUtf8("lnLugar"))
        self.horizontalLayout_2.addWidget(self.lnLugar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_38 = QtGui.QLabel(self.widget)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_3.addWidget(self.label_38)
        self.lnNac = QtGui.QLineEdit(self.widget)
        self.lnNac.setObjectName(_fromUtf8("lnNac"))
        self.horizontalLayout_3.addWidget(self.lnNac)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.cBCivil = QtGui.QComboBox(self.widget)
        self.cBCivil.setObjectName(_fromUtf8("cBCivil"))
        self.cBCivil.addItem(_fromUtf8(""))
        self.cBCivil.addItem(_fromUtf8(""))
        self.cBCivil.addItem(_fromUtf8(""))
        self.cBCivil.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cBCivil)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.cBHijos = QtGui.QComboBox(self.widget)
        self.cBHijos.setObjectName(_fromUtf8("cBHijos"))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.cBHijos.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cBHijos)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.lnFamiliar = QtGui.QLineEdit(self.widget)
        self.lnFamiliar.setObjectName(_fromUtf8("lnFamiliar"))
        self.horizontalLayout_3.addWidget(self.lnFamiliar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.lnCalle = QtGui.QLineEdit(self.widget)
        self.lnCalle.setObjectName(_fromUtf8("lnCalle"))
        self.horizontalLayout_4.addWidget(self.lnCalle)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_4.addWidget(self.label_14)
        self.lnNum = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnNum.sizePolicy().hasHeightForWidth())
        self.lnNum.setSizePolicy(sizePolicy)
        self.lnNum.setObjectName(_fromUtf8("lnNum"))
        self.horizontalLayout_4.addWidget(self.lnNum)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.lnPiso = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnPiso.sizePolicy().hasHeightForWidth())
        self.lnPiso.setSizePolicy(sizePolicy)
        self.lnPiso.setObjectName(_fromUtf8("lnPiso"))
        self.horizontalLayout_4.addWidget(self.lnPiso)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.lnDepto = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnDepto.sizePolicy().hasHeightForWidth())
        self.lnDepto.setSizePolicy(sizePolicy)
        self.lnDepto.setObjectName(_fromUtf8("lnDepto"))
        self.horizontalLayout_4.addWidget(self.lnDepto)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_5.addWidget(self.label_17)
        self.lnLocal = QtGui.QLineEdit(self.widget)
        self.lnLocal.setObjectName(_fromUtf8("lnLocal"))
        self.horizontalLayout_5.addWidget(self.lnLocal)
        spacerItem8 = QtGui.QSpacerItem(37, 13, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.lnPartido = QtGui.QLineEdit(self.widget)
        self.lnPartido.setObjectName(_fromUtf8("lnPartido"))
        self.horizontalLayout_5.addWidget(self.lnPartido)
        spacerItem9 = QtGui.QSpacerItem(37, 13, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        self.lnCP = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnCP.sizePolicy().hasHeightForWidth())
        self.lnCP.setSizePolicy(sizePolicy)
        self.lnCP.setObjectName(_fromUtf8("lnCP"))
        self.horizontalLayout_5.addWidget(self.lnCP)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lnTel = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnTel.sizePolicy().hasHeightForWidth())
        self.lnTel.setSizePolicy(sizePolicy)
        self.lnTel.setObjectName(_fromUtf8("lnTel"))
        self.horizontalLayout_6.addWidget(self.lnTel)
        self.label_21 = QtGui.QLabel(self.widget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.lnMov = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnMov.sizePolicy().hasHeightForWidth())
        self.lnMov.setSizePolicy(sizePolicy)
        self.lnMov.setObjectName(_fromUtf8("lnMov"))
        self.horizontalLayout_6.addWidget(self.lnMov)
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.lnMail = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnMail.sizePolicy().hasHeightForWidth())
        self.lnMail.setSizePolicy(sizePolicy)
        self.lnMail.setObjectName(_fromUtf8("lnMail"))
        self.horizontalLayout_6.addWidget(self.lnMail)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_24.setBuddy(self.lntitulo)
        self.label_27.setBuddy(self.lnEscuela)
        self.label_25.setBuddy(self.lnDistrito)
        self.label_28.setBuddy(self.lnOtros)
        self.label_29.setBuddy(self.lnInsti1)
        self.label_30.setBuddy(self.lnInsti2)
        self.label.setBuddy(self.cBCarrera)
        self.label_2.setBuddy(self.lnCiclo)
        self.label_23.setBuddy(self.lnAct)
        self.label_35.setBuddy(self.lnHorario)
        self.label_36.setBuddy(self.lnOS)
        self.label_37.setBuddy(self.lnTelEmer)
        self.label_4.setBuddy(self.lnNombre)
        self.label_5.setBuddy(self.cBSexo)
        self.label_7.setBuddy(self.lnDni)
        self.label_8.setBuddy(self.dENac)
        self.label_9.setBuddy(self.lnLugar)
        self.label_38.setBuddy(self.lnNac)
        self.label_10.setBuddy(self.cBCivil)
        self.label_11.setBuddy(self.cBHijos)
        self.label_12.setBuddy(self.lnFamiliar)
        self.label_13.setBuddy(self.lnCalle)
        self.label_14.setBuddy(self.lnNum)
        self.label_15.setBuddy(self.lnPiso)
        self.label_16.setBuddy(self.lnDepto)
        self.label_17.setBuddy(self.lnLocal)
        self.label_18.setBuddy(self.lnPartido)
        self.label_19.setBuddy(self.lnCP)
        self.label_20.setBuddy(self.lnTel)
        self.label_21.setBuddy(self.lnMov)
        self.label_22.setBuddy(self.lnMail)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cBCarrera, self.lnCiclo)
        Form.setTabOrder(self.lnCiclo, self.lnNombre)
        Form.setTabOrder(self.lnNombre, self.cBSexo)
        Form.setTabOrder(self.cBSexo, self.sBEdad)
        Form.setTabOrder(self.sBEdad, self.lnDni)
        Form.setTabOrder(self.lnDni, self.dENac)
        Form.setTabOrder(self.dENac, self.lnLugar)
        Form.setTabOrder(self.lnLugar, self.lnDepto)
        Form.setTabOrder(self.lnDepto, self.lnNum)
        Form.setTabOrder(self.lnNum, self.lnCalle)
        Form.setTabOrder(self.lnCalle, self.lnPartido)
        Form.setTabOrder(self.lnPartido, self.lnLocal)
        Form.setTabOrder(self.lnLocal, self.lnTel)
        Form.setTabOrder(self.lnTel, self.lnCP)
        Form.setTabOrder(self.lnCP, self.lnPiso)
        Form.setTabOrder(self.lnPiso, self.cBHijos)
        Form.setTabOrder(self.cBHijos, self.lnFamiliar)
        Form.setTabOrder(self.lnFamiliar, self.lnMov)
        Form.setTabOrder(self.lnMov, self.lnMail)
        Form.setTabOrder(self.lnMail, self.BtnOk)
        Form.setTabOrder(self.BtnOk, self.BtnCancel)
        Form.setTabOrder(self.BtnCancel, self.rBtnSi)
        Form.setTabOrder(self.rBtnSi, self.rBtnNo)
        Form.setTabOrder(self.rBtnNo, self.cBDni)
        Form.setTabOrder(self.cBDni, self.cBTit)
        Form.setTabOrder(self.cBTit, self.cBReg)
        Form.setTabOrder(self.cBReg, self.cBFoto)
        Form.setTabOrder(self.cBFoto, self.cBCert)
        Form.setTabOrder(self.cBCert, self.lnAct)
        Form.setTabOrder(self.lnAct, self.lnHorario)
        Form.setTabOrder(self.lnHorario, self.lnOS)
        Form.setTabOrder(self.lnOS, self.lnTelEmer)
        Form.setTabOrder(self.lnTelEmer, self.cBCivil)
        Form.setTabOrder(self.cBCivil, self.lntitulo)
        Form.setTabOrder(self.lntitulo, self.dEEgr)
        Form.setTabOrder(self.dEEgr, self.lnEscuela)
        Form.setTabOrder(self.lnEscuela, self.lnDistrito)
        Form.setTabOrder(self.lnDistrito, self.lnOtros)
        Form.setTabOrder(self.lnOtros, self.lnInsti1)
        Form.setTabOrder(self.lnInsti1, self.dEEgr_2)
        Form.setTabOrder(self.dEEgr_2, self.lnInsti2)
        Form.setTabOrder(self.lnInsti2, self.dEEgr_3)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Datos Personales del alumno</span></p></body></html>", None))
        self.label_33.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Estudios Cursados</span></p></body></html>", None))
        self.label_34.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Datos Laborales</span></p></body></html>", None))
        self.gBoxTrab.setTitle(_translate("Form", "Trabaja", None))
        self.rBtnSi.setText(_translate("Form", "Sí", None))
        self.rBtnNo.setText(_translate("Form", "No", None))
        self.gBDocs.setTitle(_translate("Form", "Documentación Presentada", None))
        self.cBDni.setText(_translate("Form", "Fotocpoia DNI", None))
        self.cBTit.setText(_translate("Form", "Fotocopia Título Secundario/Polimodal", None))
        self.cBReg.setText(_translate("Form", "Número de registro", None))
        self.cBFoto.setText(_translate("Form", "Fotos", None))
        self.cBCert.setText(_translate("Form", "Certificado Médico", None))
        self.BtnOk.setText(_translate("Form", "&Siguiente >>", None))
        self.BtnCancel.setText(_translate("Form", "&Limpiar", None))
        self.label_24.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Título nivel medio o polimodal</span></p></body></html>", None))
        self.label_26.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Año de Egreso</span></p></body></html>", None))
        self.dEEgr.setDisplayFormat(_translate("Form", "yyyy", None))
        self.label_27.setText(_translate("Form", "Escuela", None))
        self.label_25.setText(_translate("Form", "Distrito", None))
        self.label_28.setText(_translate("Form", "Otros Estudios", None))
        self.label_29.setText(_translate("Form", "Institución", None))
        self.label_31.setText(_translate("Form", "Año de Egreso", None))
        self.dEEgr_2.setDisplayFormat(_translate("Form", "yyyy", None))
        self.label_30.setText(_translate("Form", "Institución", None))
        self.label_32.setText(_translate("Form", "Año de Egreso", None))
        self.dEEgr_3.setDisplayFormat(_translate("Form", "yyyy", None))
        self.label.setText(_translate("Form", "Carrera", None))
        self.cBCarrera.setItemText(0, _translate("Form", "FOBA", None))
        self.cBCarrera.setItemText(1, _translate("Form", "Tecnicatura", None))
        self.cBCarrera.setItemText(2, _translate("Form", "Profesorado de Artes Plásticas", None))
        self.cBCarrera.setItemText(3, _translate("Form", "Cursos Extraprogramáticos", None))
        self.label_2.setText(_translate("Form", "Año", None))
        self.lnCiclo.setToolTip(_translate("Form", "Año del Ciclo Lectivo", None))
        self.lnCiclo.setInputMask(_translate("Form", "9999", None))
        self.label_23.setText(_translate("Form", "Actividad", None))
        self.label_35.setText(_translate("Form", "Horario Habitual", None))
        self.label_36.setText(_translate("Form", "Obra Social", None))
        self.label_37.setText(_translate("Form", "Teléfono de Emergencias", None))
        self.label_4.setText(_translate("Form", "Apellido y Nombres", None))
        self.label_5.setText(_translate("Form", "Sexo", None))
        self.cBSexo.setItemText(0, _translate("Form", "Femenino", None))
        self.cBSexo.setItemText(1, _translate("Form", "Masculino", None))
        self.label_6.setText(_translate("Form", "Edad", None))
        self.label_7.setText(_translate("Form", "Documento único", None))
        self.label_8.setText(_translate("Form", "Fecha de Nacimiento", None))
        self.dENac.setDisplayFormat(_translate("Form", "dd/MM/yyyy", None))
        self.label_9.setText(_translate("Form", "Lugar de Nacimiento", None))
        self.label_38.setText(_translate("Form", "Nacionalidad", None))
        self.label_10.setText(_translate("Form", "Estado civil", None))
        self.cBCivil.setItemText(0, _translate("Form", "Solterx", None))
        self.cBCivil.setItemText(1, _translate("Form", "Casadx", None))
        self.cBCivil.setItemText(2, _translate("Form", "Divorciadx", None))
        self.cBCivil.setItemText(3, _translate("Form", "En Convivencia", None))
        self.label_11.setText(_translate("Form", "Hijos", None))
        self.cBHijos.setItemText(0, _translate("Form", "No", None))
        self.cBHijos.setItemText(1, _translate("Form", "1", None))
        self.cBHijos.setItemText(2, _translate("Form", "2", None))
        self.cBHijos.setItemText(3, _translate("Form", "3", None))
        self.cBHijos.setItemText(4, _translate("Form", "4", None))
        self.cBHijos.setItemText(5, _translate("Form", "5", None))
        self.cBHijos.setItemText(6, _translate("Form", "6", None))
        self.cBHijos.setItemText(7, _translate("Form", "7", None))
        self.cBHijos.setItemText(8, _translate("Form", "8", None))
        self.cBHijos.setItemText(9, _translate("Form", "9", None))
        self.cBHijos.setItemText(10, _translate("Form", "10", None))
        self.label_12.setText(_translate("Form", "Familiares a Cargo", None))
        self.label_13.setText(_translate("Form", "Domicilio - Calle", None))
        self.label_14.setText(_translate("Form", "N°", None))
        self.label_15.setText(_translate("Form", "Piso", None))
        self.label_16.setText(_translate("Form", "Depto", None))
        self.label_17.setText(_translate("Form", "Localidad/Barrio", None))
        self.label_18.setText(_translate("Form", "Partido", None))
        self.label_19.setText(_translate("Form", "CP", None))
        self.label_20.setText(_translate("Form", "Teléfono", None))
        self.label_21.setText(_translate("Form", "Móvil", None))
        self.label_22.setText(_translate("Form", "Correo Electrónico", None))

